### ISSUE TITLE
ScrollX true with Responsive set to false doesn't work

### ISSUE THREAD

**Issue by PrzemyslawKlys** [DataTables/DataTablesSrc#143]
I wanted to set responsive to false and enable scrollX. It doesn't work. It works if I remove responsive options altogether. Probably makes sense to have some logic that takes care of this.

```
responsive: false,
"responsive": {
    "details": false
},
"select": true,
"searching": true,
"stateSave": true,
"columnDefs": "",
scrollX: true
```

Fiddle showing this issue: https://jsfiddle.net/6mp0e4ky/1/

**Comment by DataTables** [comment]
```
responsive: false,
"responsive": {
    "details": false
},
```

while its technically valid Javascript, its also impossible Javascript. `responsive` can't both be `false` and an object at the same time! The second one is the one that wins there, so you actually just have:

```
"responsive": {
    "details": false
},
```

which enables Responsive with details disabled.

There isn't any logic we can add to handle that case, since the object is never created with two `responsive` properties.

**Comment by PrzemyslawKlys** [comment]
I see. Thanks! Sorry
