### ISSUE TITLE
Setting for pagination button count

### ISSUE THREAD

**Issue by easyest** [DataTables/DataTablesSrc#26]
It would be nice to have possibility to control pagination button count for `simple_numbers` and `full_numbers`. Such setting, available for `_numbers` function would let the function how many buttons to return.

**Comment by DataTables** [comment]
In the fix committed above the block you note does correctly take the paging button count into account. It must be >= 5 and be an odd number in order to be able to operate with the built in paging options. For something smaller than 5 (i.e. 3) a custom paging plug-in would be required.

Thanks for letting me know about this!
