### ISSUE TITLE
Column sorting is much slower in v2

### ISSUE THREAD

**Issue by xPaw** [DataTables/DataTablesSrc#260]
After updating to v2, I noticed that sorting columns takes multiple seconds now on a table with 15k rows, specifically in this function:

https://github.com/DataTables/DataTablesSrc/blob/0080bcc77a495e0a2a1af6cdbf97a462ec16d813/js/core/core.sort.js#L66-L73

Chrome:
![image](https://github.com/DataTables/DataTablesSrc/assets/613331/84004999-e8c0-405e-b47d-970e6973d41c)

It is also much slower in Firefox:
![image](https://github.com/DataTables/DataTablesSrc/assets/613331/8636c3d5-b62e-4b8a-94aa-9742d4a4b860)

Repro:
1. https://datatables.net/extensions/searchpanes/examples/performance/searchPanes50k.html
2. Click any column in the bottom table.

Chrome 121 and Firefox 124.

**Comment by AllanJard** [comment]
I've just made two commits that brings the time for sorting on that example (for me on my computer) from 21S to 78mS. That was done by trading cache memory for speed - rather than always computing the `indexOf` values, I use two maps to do it, and, well, the difference speaks for itself.

Thanks for flagging it up!

**Comment by AllanJard** [comment]
Very excellent point - thanks for finding that and letting me know. I've just committed a change to address that.
