### ISSUE TITLE
Setting `typeDetect: false` breaks ordering

### ISSUE THREAD

**Issue by jlherren** [DataTables/DataTablesSrc#303]
When disabling type detection with `typeDetect: false`, it no longer correctly orders the table according to the data attributes.

See example: https://live.datatables.net/zeyobure/2/edit?html,js,output

**Comment by AllanJard** [comment]
I'm not sure why you would expect the ordering to work in such a case? Type detection is used for the ordering. Detect the type so it can be sorted correctly.

What is you intention with disabling the type detection there?

**Comment by jlherren** [comment]
I expected it to work, because it has always worked, long before type detection even existed.

I summarized my reasons for not wanting it here: https://datatables.net/forums/discussion/comment/236449/#Comment_236449

Perhaps I need to rethink my approach. It's not that I don't want type detection, I just don't want any of those CSS classes it sets on the columns by default. Maybe I just have to override all those `text-align: right`. I guess there's no way to have DataTables not set these classes at all? Setting `typeDetect: false` just seemed like the easiest solution, but I'm happy fixing it with just CSS if that won't work.

**Comment by AllanJard** [comment]
Ah! You are referring to the column text alignment if I understand correctly? I'm with you now and was confused by the terminology. DataTables has always done type detection, which is why I was confused - it needs to be able to tell if a column is numeric, string, date, etc for sorting. With 2.0 I added automatic text alignment based on the detected type. That appears to be what you are wanting to disable? Not everything else that comes from type detection!

To disable the text alignment class for `num` (numeric) data, use:

```js
DataTable.type('num', 'className', '');
```

Example here: https://live.datatables.net/hedufucu/1/edit .

Note that the "Age" column now has no extra class. The Salary column is still right aligned since it is a `num-fmt` column type.

**Comment by jlherren** [comment]
Yes, exactly. I didn't know that type detection was always a thing, so I thought it came with the new alignment feature. [Based on typography.scss](https://github.com/DataTables/DataTablesSrc/blob/7d5c19aa5a5b8e859ae3539cc20accadbce53829/css/typography.scss#L40) I guess I do that for type `num` and `date` it'll be exactly as I want.

Thank you so much for explaining!
